/**
    @author: Amarendra Kumar
    @company: Saasfocus
    @description: Common class for all the constant use in apex classes
**/
public  With Sharing class MBFS_Constant {

    public static String MBFS_RTM_FUTURE_DURATION = 'Future';
    public static String MBSF_MONTH = 'MBSF_MONTH';
    public static String ALL = 'All';
    public static String NOT_ASSIGNED = 'NOT_ASSIGNED';
    public static String ZERO = 'ZERO';
    public static String GREATER_ZERO = 'GREATER_ZERO';
    public static String MBSF_CAMPAIGN = 'MBSF_CAMPAIGN';
    public static String MBSF_LEAD    = 'MBSF_LEAD'; 
    public static String NONE = 'None'; 
    public static String TODAY = 'Today';
    public static String TODAY_OVERDUE= 'Today_OverDue';
    public static String OVERDUE    = 'OverDue';
    public static String NONE_PICKLIST    = '--None--';
    public static String NON_AGILITY    = 'Non-Agility';
    public static String MERCEDES    = 'Mercedes';
    public static String NON_MERCEDES    = 'Non_Mercedes';
}